describe('Register testovi', () => {
    it ('Posetite stranicu', () => {
        cy.visit('/')
    })
    it ('Kliknti na register',() => {
        cy.visit('/')
        cy.get('.nav-link').eq(1).click()
    })
    it ('Register with invalid email', () => {
        cy.visit ('/')
        cy.get('a[href="/register"]').click()
        cy.get('#first-name').type('Sara')
        cy.get('#last-name').type('Stanacev')
        cy.get('#email').type('sara97@testcom')
        cy.get('#password').type('test123123')
        cy.get('#password-confirmation').type('test123123')
        cy.get('.form-check-input').click()
        cy.get('.btn.btn-custom').click
    })
    it ('Register with invalid password-confirmation', () => {
        cy.visit ('/')
        cy.get('a[href="/register"]').click()
        cy.get('#first-name').type('Sara')
        cy.get('#last-name').type('Stanacev')
        cy.get('#email').type('sara97@test.com')
        cy.get('#password').type('test123123')
        cy.get('#password-confirmation').type('test12312')
        cy.get('.form-check-input').click()
        cy.get('.btn.btn-custom').click()
    })
    it ('Register without accepting Terms and Conditions', () => {
        cy.visit ('/')
        cy.get('a[href="/register"]').click()
        cy.get('#first-name').type('Sara')
        cy.get('#last-name').type('Stanacev')
        cy.get('#email').type('sara97@test.com')
        cy.get('#password').type('test123123')
        cy.get('#password-confirmation').type('test123123')
        cy.get('.btn.btn-custom').click()
    })
    it ('Register', () => {
        cy.visit ('/')
        cy.get('a[href="/register"]').click()
        cy.get('#first-name').type('Sara')
        cy.get('#last-name').type('Stanacev')
        cy.get('#email').type('sara97@test.com')
        cy.get('#password').type('test123123')
        cy.get('#password-confirmation').type('test123123')
        cy.get('.form-check-input').click()
        cy.get('.btn.btn-custom').click()
    })
    it ('Kliknuti na logout', () => {
        cy.visit('/')
        cy.get('a[href="/login"]').click()
        cy.get('#email').type('sara97@test.com')
        cy.get('#password').type('test123123')
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 4)
        cy.get('.nav-link').eq(3).click()
    })
    it ('Login with valid credentials', () => {
        cy.visit ('/')
        cy.get('a[href="/login"]').click()
        cy.get('#email').type('sara97@test.com')
        cy.get('#password').type('test123123')
        cy.get('button').click()
    })
    it ('Kliknuti na logout', () => {
        cy.visit('/')
        cy.get('a[href="/login"]').click()
        cy.get('#email').type('sara97@test.com')
        cy.get('#password').type('test123123')
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 4)
        cy.get('.nav-link').eq(3).click()
    })
})